"""Catalog of every simulated condition: class, category, and the
educational content shown in the Accessibility Simulator panel.

Sources used for the medical descriptions and mechanics (see each entry's
refs): National Eye Institute (NEI), American Academy of Ophthalmology
(AAO), NINDS, NIDCD, Vestibular Disorders Association (VeDA), American
Migraine Foundation (AMF), Machado et al. 2009 (IEEE TVCG, via PubMed),
International Dyslexia Association. This simulation is an educational
approximation — individual experiences vary and cannot be perfectly
represented.
"""
from .visual import (Glaucoma, MacularDegeneration, Cataracts,
                     DiabeticRetinopathy, RetinitisPigmentosa,
                     Protanopia, Deuteranopia, Tritanopia,
                     VisualSnow, MigraineAura, Oscillopsia)
from .audio_fx import HearingLoss, Tinnitus, AuditoryProcessing
from .movement import ParkinsonianTremor, EssentialTremor, VestibularDisorder
from .cognitive import (Prosopagnosia, HemispatialNeglect, ADHDDistraction,
                        MemoryImpairment)

DISCLAIMER = ('This lab demonstrates selected barriers and effects; it does not reproduce\n'
              'every person\'s lived experience. Experiences vary between individuals.')

PRESETS = {'mild': .3, 'moderate': .6, 'severe': .9}


def _e(cls, cat, name, desc, medical, gameplay, misconception, assistive, refs):
    return dict(cls=cls, cat=cat, name=name, desc=desc, medical=medical,
                gameplay=gameplay, misconception=misconception,
                assistive=assistive, refs=refs)


EFFECTS = {
    # ------------------------------------------------------------- visual
    'glaucoma': _e(Glaucoma, 'visual', 'Glaucoma',
        'Loss of peripheral vision - "tunnel vision".',
        'Optic-nerve damage, usually from raised eye pressure, kills\nperipheral vision first; central acuity survives longest.',
        'Your field of view shrinks. Threats approach unseen from the\nsides - you must physically turn to scan the world.',
        'Myth: "it looks like black binoculars". Early loss is subtle\nand unnoticed - half of those affected don\'t know they have it.',
        'Eye-pressure medication, laser surgery; early screening.\nIn games: minimaps, audio cues, edge-of-screen indicators.',
        'NEI: Glaucoma | AAO EyeWiki: POAG'),
    'macular': _e(MacularDegeneration, 'visual', 'Macular Degeneration (AMD)',
        'A blind smudge exactly where you look; periphery preserved.',
        'The macula (central retina) degenerates with age. Faces and\ntext vanish into the scotoma while side vision stays intact.',
        'The thing you look at is the thing you cannot see - read signs\nby looking slightly away from them (eccentric viewing).',
        'Myth: AMD leads to total blindness. It almost never does -\nperipheral vision is typically preserved.',
        'Magnifiers, large print, audiobooks, eccentric-viewing training,\nanti-VEGF injections for wet AMD.',
        'NEI: Age-Related Macular Degeneration'),
    'cataracts': _e(Cataracts, 'visual', 'Cataracts',
        'Cloudy lens: haze, glare, faded colors, low contrast.',
        'The crystalline lens yellows and clouds, scattering light.\nGlare around lights, washed-out contrast, dulled colors.',
        'Bright windows and lamps bloom into veils of light; similar\ncolors blend together. Night scenes are hardest.',
        'Myth: cataracts must "ripen" before surgery. Modern surgery is\ndone whenever vision interferes with life.',
        'Cataract surgery (one of the safest operations worldwide);\nbetter lighting, anti-glare sunglasses meanwhile.',
        'NEI: Cataracts | AAO: Cataract surgery facts'),
    'retinopathy': _e(DiabeticRetinopathy, 'visual', 'Diabetic Retinopathy',
        'Dark blotches, floaters, and vision that fluctuates.',
        'High blood sugar damages retinal vessels: hemorrhages blot out\npatches of the field; acuity swings with glucose levels.',
        'Random dark islands hide parts of the world; floaters drift\nwith your gaze; sharpness comes and goes in slow waves.',
        'Myth: only poorly-controlled diabetes is affected. Duration of\ndiabetes matters too - screening is for everyone with it.',
        'Laser treatment, anti-VEGF injections, blood-sugar management,\nannual dilated eye exams.',
        'NEI: Diabetic Retinopathy'),
    'rp': _e(RetinitisPigmentosa, 'visual', 'Retinitis Pigmentosa',
        'Tunnel vision plus severe night blindness.',
        'Inherited rod-then-cone degeneration: night vision fails years\nbefore the daytime field narrows into a tunnel.',
        'Dark scenes are near-impossible while lit rooms stay workable.\nTry the zombie street to feel the asymmetry.',
        'Myth: RP means darkness from birth. Onset is gradual, often\ndiagnosed in adolescence via night blindness.',
        'Mobility (cane) training, high-lumen flashlights, gene therapy\n(voretigene) for specific mutations.',
        'NEI: Retinitis Pigmentosa'),
    'protanopia': _e(Protanopia, 'visual', 'Protanopia (red-blind)',
        'Red cone absent: reds darken and merge with greens.',
        'L-cone photopigment missing (~1% of males). Reds appear dark;\nred/green, orange/yellow pairs collapse together.',
        'Red markers vanish against dark ground; "red = danger" coding\nfails completely. Machado 2009 matrices, slider = severity.',
        'Myth: color blindness = seeing gray. Dichromats see color -\njust a compressed two-axis version.',
        'Color-blind-safe palettes, shape/pattern coding, filter apps.\nDesign rule: never encode meaning in hue alone.',
        'Machado et al. 2009 IEEE TVCG (PubMed); NEI: Color Blindness'),
    'deuteranopia': _e(Deuteranopia, 'visual', 'Deuteranopia (green-blind)',
        'Green cone absent: the most common dichromacy.',
        'M-cone missing. Greens/reds/browns crowd into muddy sameness;\nblues and yellows survive best.',
        'Grass, brick and skin tones converge; the green safehouse door\nreads as gray-yellow. Slider = severity.',
        'Myth: "red-green colorblind" people confuse only red & green.\nMany pairs collapse: purple/blue, green/brown, ...',
        'Same as protanopia: redundant coding, safe palettes.',
        'Machado et al. 2009 IEEE TVCG (PubMed); NEI: Color Blindness'),
    'tritanopia': _e(Tritanopia, 'visual', 'Tritanopia (blue-blind)',
        'Rare S-cone loss: blue/yellow axis collapses.',
        'S-cone missing (rare, not sex-linked). Blues and greens merge;\nyellows and pinks wash toward white.',
        'The sky, water and blue UI elements lose their identity.\nSlider = severity.',
        'Myth: all color blindness is red-green. Tritan defects exist\nand are often acquired (aging, diabetes, glaucoma).',
        'Safe palettes; avoid blue/green and yellow/white contrasts.',
        'Machado et al. 2009 IEEE TVCG (PubMed)'),
    'visual_snow': _e(VisualSnow, 'visual', 'Visual Snow Syndrome',
        'Constant static over vision, flicker, floaters, glare.',
        'A neurological (not ocular) disorder: persistent TV-like\nstatic, palinopsia, photophobia, entoptic phenomena.',
        'Film grain never leaves the screen; lights bloom; bright\nspecks dart along arcs (blue-field entoptic). Noise slider.',
        'Myth: "everyone sees that". The static is constant and can be\ndisabling; it is a recognized syndrome (ICHD).',
        'Tinted lenses (FL-41), managing comorbid migraine; research\nongoing - no cure yet.',
        'NINDS; Visual Snow Initiative; AMF'),
    'migraine': _e(MigraineAura, 'visual', 'Migraine Aura',
        'An expanding shimmering blind arc, ~1-minute cycles.',
        'Cortical spreading depression marches across the visual\ncortex: a scintillating zigzag arc grows over ~20 min\n(compressed here), leaving a temporary blind wake.',
        'A flickering C-shape sweeps outward and hides what it covers;\nthe world ripples. Reading mid-aura is nearly impossible.',
        'Myth: migraine = a bad headache. Aura alone can occur without\npain and still disable (driving, reading, working).',
        'Dark quiet rooms, triptans/CGRP medication, trigger tracking.',
        'American Migraine Foundation: Visual Aura'),
    'oscillopsia': _e(Oscillopsia, 'visual', 'Oscillopsia',
        'The world bounces - gaze stabilization has failed.',
        'Vestibulo-ocular reflex damage (e.g. gentamicin toxicity) or\nnystagmus: the image smears with every head movement.',
        'Continuous micro-shake plus motion blur; aiming and reading\nrequire standing perfectly still.',
        'Myth: it is dizziness. Oscillopsia is visual - the WORLD moves,\nnot the room spinning inside your head.',
        'Vestibular rehabilitation therapy; treating the cause.',
        'VeDA: Oscillopsia | NINDS'),
    # ------------------------------------------------------------- audio
    'hearing_loss': _e(HearingLoss, 'audio', 'Hearing Loss',
        'Muffled, attenuated sound; high frequencies go first.',
        'Sensorineural loss attenuates and low-passes hearing -\nconsonants (s, t, f) vanish before vowels do.',
        'Every cue is quieter and muffled; directionality degrades.\nStack with scenarios to miss what others catch.',
        'Myth: hearing aids restore normal hearing. They amplify -\nclarity in noise often remains hard.',
        'Hearing aids, cochlear implants, captions, FM systems,\nspeech-to-text apps.',
        'NIDCD: Hearing Loss'),
    'tinnitus': _e(Tinnitus, 'audio', 'Tinnitus',
        'A ring that never stops. Pitch/side configurable in code.',
        'Phantom auditory perception, usually a 4-8 kHz tone, often\naccompanying noise-induced hearing loss.',
        'A constant tone sits on top of everything; quiet scenes are\nworst - there is no silence anymore. Slider = loudness.',
        'Myth: nothing can be done. Sound therapy and CBT measurably\nreduce distress for most people.',
        'Sound maskers, hearing aids, CBT, avoiding loud exposure.',
        'NIDCD: Tinnitus | ATA'),
    'apd': _e(AuditoryProcessing, 'audio', 'Auditory Processing Disorder',
        'Hearing is fine; decoding is late and smeared.',
        'The brain mis-times and mis-orders intact auditory input:\nspeech in noise, localization and sequencing all suffer.',
        'Sounds arrive noticeably late and speech overlaps itself -\nyou react a beat after everyone else.',
        'Myth: APD = not listening. The ears work; the decoding lags.\nRepeating louder does not help; rephrasing does.',
        'Preferential seating, written instructions, FM systems,\nslower/rephrased speech.',
        'NIDCD; ASHA: (C)APD'),
    # ----------------------------------------------------------- movement
    'parkinsonian': _e(ParkinsonianTremor, 'movement', 'Parkinsonian Tremor',
        '4-6 Hz resting tremor + delayed movement initiation.',
        'Dopamine loss in the basal ganglia: resting tremor, slowness\n(bradykinesia) and hesitant starts.',
        'Crosshair shakes worst when you are still; movement begins a\nbeat after you press the key, then ramps up.',
        'Myth: tremor is the whole disease. Slowness and rigidity\nusually disable more than the shaking does.',
        'Levodopa, deep-brain stimulation, physio/occupational therapy.',
        'NINDS: Parkinson\'s Disease'),
    'essential_tremor': _e(EssentialTremor, 'movement', 'Essential Tremor',
        'Faster continuous oscillation, worse during action.',
        'The most common movement disorder (~8 Hz action tremor) -\nworst mid-movement: pouring, writing, aiming.',
        'The view oscillates continuously and amplifies while you\nmove - the inverse pattern of parkinsonian tremor.',
        'Myth: essential tremor is early Parkinson\'s. It is a distinct,\noften inherited condition.',
        'Beta-blockers, weighted utensils, wrist weights, DBS in\nsevere cases.',
        'NINDS: Tremor Fact Sheet'),
    'vestibular': _e(VestibularDisorder, 'movement', 'Vestibular Disorder',
        'Tilting horizon, drift, sway, walking imbalance.',
        'Inner-ear balance failure: the brain receives wrong motion\nsignals, so the world tilts, drifts and lurches.',
        'The horizon refuses to stay level; walking pulls sideways and\namplifies everything. Stillness is the only relief.',
        'Myth: "just dizziness". Chronic vestibular disorders affect\nwalking, reading, driving and work capacity.',
        'Vestibular rehabilitation therapy, canalith repositioning\n(BPPV), balance training.',
        'VeDA: About Vestibular Disorders'),
    # ---------------------------------------------------------- cognitive
    'prosopagnosia': _e(Prosopagnosia, 'cognitive', 'Prosopagnosia',
        'Face blindness: identify people by clothing and context.',
        'Fusiform face area dysfunction (congenital ~2%, or acquired):\nfaces perceive fine but never resolve into identities.',
        'Every face becomes an anonymous oval; dialogue names turn\ninto "person in the red shirt" - track people by clothes.',
        'Myth: faces look blurry. They look normal - they simply fail\nto *mean* anyone.',
        'Deliberate cue strategies (voice, gait, hair, clothing),\ndisclosure scripts for social settings.',
        'NINDS: Prosopagnosia'),
    'neglect': _e(HemispatialNeglect, 'cognitive', 'Hemispatial Neglect',
        'The left side of the world stops being attended to.',
        'Typically right-parietal stroke: not blindness, but a failure\nof attention - patients eat half the plate, shave half the face.',
        'Left-side HUD vanishes, markers on your left silently drop\nout, and objectives drift right. You won\'t notice - that IS it.',
        'Myth: patients could look left "if they tried". The deficit is\nattention itself; they do not know the left is missing.',
        'Scanning training, prism adaptation therapy, cueing from the\nright side.',
        'NINDS: Stroke - Hemispatial Neglect (parietal syndromes)'),
    'adhd_fx': _e(ADHDDistraction, 'cognitive', 'ADHD (attention capture)',
        'Intrusive distractions; the objective fades from awareness.',
        'Executive-function difference: salience wins over intention;\ninterruptions cost minutes, not seconds, to recover from.',
        'Popups hijack the screen and your objective text literally\nfades while distracted. F drags attention back.',
        'Myth: ADHD = lack of willpower. Attention is captured\ninvoluntarily; effort alone does not prevent it.',
        'Coaching, medication, environment design (quiet rooms,\nnotifications off), body-doubling, extra time.',
        'NIMH/NINDS: ADHD'),
    'memory': _e(MemoryImpairment, 'cognitive', 'Memory Impairment',
        'Objectives fade; names never stick; J = check journal.',
        'Working/episodic memory deficits (brain injury, dementia,\nchemo-fog): information decays without external anchors.',
        'The objective text fades seconds after you read it and NPCs\nare "???". Press J to consult your journal - externalize!',
        'Myth: memory loss = forgetting everything. Usually recent and\nprospective memory fail while old skills survive.',
        'Journals, phone reminders, routines, labeled environments,\nspaced repetition.',
        'NINDS: Memory disorders overviews'),
}
